// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geljeqcahnwrddmsnugl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbGplcWNhaG53cmRkbXNudWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNTgxODgsImV4cCI6MjA1NDczNDE4OH0.0twCrA9DNinSdDpl3Y3Ovzucfu9Y--aQeJddTgItjCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);